name: Demo Output
on:
  push:
    branches:
      - master

jobs:
  notify-dry-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # all history required
      - name: "Sample Dry Run of Slack Notification"
        uses: ./
        with:
          dry-run: true
          dump: true
          token: "secrets.SLACK_BOT_KEY"
          secret: "secrets.SLACK_SIGNING_SECRET"
          channel: "secrets.SLACK_CHANNEL"
          evals: |
            changelog = git --no-pager log --reverse --color=never --pretty="format:• `%h` %s (%ae)" {{context.payload.before}}...{{context.payload.after}}
          message: |
            *Sample Slack Message:*
            `{{cut context.payload.before 8}}...{{cut context.payload.after 8}}`
            {{evals.changelog}}
